local Games = {
    --id="游戏ID",name="游戏名字",type="游戏类型",friends="是否有好友房>>1好友房>>2休闲场>>3竞技场",number ="金币房人数",playerCount="人数选择",isZuoXing4="是否有4人坐省",isVisible="可见",icon="大厅按钮图片",icon1="大厅按钮图片1",icons="大厅按钮图片2",icon8="八字玩法图片",ruleBtn="规则按钮图片",ruleCSB="规则网页节点",imgSynopsiss="游戏简介图片",imgSynopsis="游戏简介图片",luaCreateRoomFile="游戏创房lua文件",luaGameFile="游戏执行lua文件",imgDesk="游戏桌面图片", rules ="规则",describe = "桌面描述",
    [16]={ id=16, name="碰胡子", type=1, clubtype=1, friends=7, number =4, playerCount = "4,3", isZuoXing4=0,isVisible=1, icon="game/zhuzhou/16/icon.png", icons="game/zhuzhou/16/icon1.png", icon1="game/zhuzhou/16/icon2.png", icon8="game/zhuzhou/16/icon8.png", ruleBtn="game/zhuzhou/16/rule.png;game/zhuzhou/16/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/wanfa/16.html", imgSynopsiss="game/zhuzhou/16/names.png", imgSynopsis="game/zhuzhou/16/name.png", luaCreateRoomFile="RoomCreateLayer16", luaGameFile="game.zhuzhou.16.GameLayer", imgDesk="game/zhuzhou/16/watermark.png", rules ="规则简介：4人同玩，无息也可胡牌，有碰即可得分，五福要报警，\n否则算平胡，双龙见牌就倒，天胡消龙消坎，但不消双龙和小七对。"}, 
    [24]={ id=24, name="衡阳十胡卡", type=1, clubtype=1, friends=7, number =3, playerCount = "3,2", isZuoXing4=0,isVisible=1, icon="game/hyphz/24/icon.png", icons="game/hyphz/24/icon1.png", icon1="game/hyphz/24/icon2.png", icon8="game/hyphz/24/icon8.png", ruleBtn="game/hyphz/24/rule.png;game/hyphz/24/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/qlphzwanfa/24.html", imgSynopsiss="game/paohuzi/24/names.png", imgSynopsis="game/paohuzi/24/name.png", luaCreateRoomFile="RoomCreateLayer24", luaGameFile="game.hyphz.24.GameLayer", imgDesk="game/paohuzi/24/watermark.png", rules ="规则简介：10胡起胡，有红黑胡，放炮包赔，10胡牌3囤，\n11胡牌1囤，12胡2囤，15胡3囤（15胡息后每3胡息加一囤）。",describe = "十胡起胡  可胡放炮"}, 
    [25]={ id=25, name="跑得快15张", type=2, clubtype=2, friends=7, number =3, playerCount = "3,2", isZuoXing4=0,isVisible=1, icon="game/puke/25/icon.png", icons="game/puke/25/icon1.png", icon1="game/puke/25/icon2.png", icon8="game/puke/25/icon8.png", ruleBtn="game/puke/25/rule.png;game/puke/25/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/wanfa/25.html", imgSynopsiss="game/puke/25/names.png", imgSynopsis="game/puke/25/name.png", luaCreateRoomFile="RoomCreateLayer25", luaGameFile="game.puke.25.GameLayer", imgDesk="game/puke/25/watermark.png", rules ="规则简介：3人玩法，去掉大小王、方块2梅花2红桃2方块A梅花A红\n桃A方块K，共45张牌，每人15张，黑桃3先出（必须带黑桃3）。"}, 
    [26]={ id=26, name="跑得快16张", type=2, clubtype=2, friends=7, number =3, playerCount = "3,2", isZuoXing4=0,isVisible=1, icon="game/puke/26/icon.png", icons="game/puke/26/icon1.png", icon1="game/puke/26/icon2.png", icon8="game/puke/26/icon8.png", ruleBtn="game/puke/26/rule.png;game/puke/26/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/wanfa/26.html", imgSynopsiss="game/puke/26/names.png", imgSynopsis="game/puke/26/name.png", luaCreateRoomFile="RoomCreateLayer25", luaGameFile="game.puke.26.GameLayer", imgDesk="game/puke/26/watermark.png", rules ="规则简介：3人玩法，去掉大小王、方块2梅花2红桃2方块A，共48张\n牌，每人16张，首局黑桃3先出。第二局开始由上游先出牌。"}, 
    [27]={ id=27, name="江永十五张", type=1, clubtype=1, friends=7, number =4, playerCount = "3,2,4", isZuoXing4=0,isVisible=1, icon="game/yongzhou/27/icon.png", icons="game/yongzhou/27/icon1.png", icon1="game/yongzhou/27/icon2.png", icon8="game/yongzhou/27/icon8.png", ruleBtn="game/yongzhou/27/rule.png;game/yongzhou/27/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/qlphzwanfa/27.html", imgSynopsiss="game/yongzhou/27/names.png", imgSynopsis="game/yongzhou/27/name.png", luaCreateRoomFile="RoomCreateLayer27", luaGameFile="game.yongzhou.27.GameLayer", imgDesk="game/yongzhou/27/watermark.png", rules ="规则简介：6胡起胡，1张王霸，王霸可以代替任何牌，有王霸可以\n不必胡，王霸不能打出，有翻醒跟醒，黄庄有王霸需赔王霸钱。", describe = "十五胡起胡  胡摸的牌"},
    [31]={ id=31, name="永州扯胡子", type=1, clubtype=1, friends=7, number =3, playerCount = "3,2,4", isZuoXing4=1,isVisible=1, icon="game/yongzhou/31/icon.png", icons="game/yongzhou/31/icon1.png", icon1="game/yongzhou/31/icon2.png", icon8="game/yongzhou/31/icon8.png", ruleBtn="game/yongzhou/31/rule.png;game/yongzhou/31/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/qlphzwanfa/31.html", imgSynopsiss="game/yongzhou/31/names.png", imgSynopsis="game/yongzhou/31/name.png", luaCreateRoomFile="RoomCreateLayer31", luaGameFile="game.yongzhou.31.GameLayer", imgDesk="game/yongzhou/31/watermark.png", rules ="规则简介：15胡起胡，2张王霸，王霸可以代替任何牌，有王霸只\n能自摸，王霸不能打出，有翻醒跟醒，黄庄有王霸需赔王霸钱。", describe = "十五胡起胡  胡摸的牌"},
    [34]={ id=34, name="祁阳落地扫", type=1, clubtype=1, friends=7, number =4, playerCount = "4,2,3", isZuoXing4=0,isVisible=1, icon="game/yongzhou/34/icon.png", icons="game/yongzhou/34/icon1.png", icon1="game/yongzhou/34/icon2.png", icon8="game/yongzhou/34/icon8.png", ruleBtn="game/yongzhou/34/rule.png;game/yongzhou/34/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/qlphzwanfa/34.html", imgSynopsiss="game/yongzhou/34/names.png", imgSynopsis="game/yongzhou/34/name.png", luaCreateRoomFile="RoomCreateLayer34", luaGameFile="game.yongzhou.34.GameLayer", imgDesk="game/yongzhou/34/watermark.png", rules ="规则简介：6胡起胡，1张王霸，王霸可以代替任何牌，有王霸可以\n不必胡，王霸不能打出，有翻醒跟醒，黄庄有王霸需赔王霸钱。", describe = "十五胡起胡  胡摸的牌"},
    [36]={ id=36, name="双王扯胡子", type=1, clubtype=1, friends=7, number =3, playerCount = "3,4", isZuoXing4=1,isVisible=1, icon="game/yongzhou/36/icon.png", icons="game/yongzhou/36/icon1.png", icon1="game/yongzhou/36/icon2.png", icon8="game/yongzhou/36/icon8.png", ruleBtn="game/yongzhou/36/rule.png;game/yongzhou/36/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/qlphzwanfa/36.html", imgSynopsiss="game/yongzhou/36/names.png", imgSynopsis="game/yongzhou/36/name.png", luaCreateRoomFile="RoomCreateLayer36", luaGameFile="game.yongzhou.36.GameLayer", imgDesk="game/yongzhou/36/watermark.png", rules ="规则简介：15胡起胡，2张王霸，王霸可以代替任何牌，有王霸只\n能自摸，王霸不能打出，有翻醒跟醒，黄庄有王霸需赔王霸钱。", describe = "十五胡起胡  胡摸的牌"},
    [38]={ id=38, name="十五胡抢", type=1, clubtype=1, friends=7, number =3, playerCount = "3", isZuoXing4=0,isVisible=1, icon="game/cdphz/38/icon.png", icons="game/cdphz/38/icon1.png", icon1="game/cdphz/38/icon2.png", icon8="game/cdphz/38/icon8.png", ruleBtn="game/paohuzi/38/rule.png;game/paohuzi/38/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/qlphzwanfa/38.html", imgSynopsiss="game/paohuzi/38/names.png", imgSynopsis="game/paohuzi/38/name.png", luaCreateRoomFile="RoomCreateLayer38", luaGameFile="game.cdphz.38.GameLayer", imgDesk="game/paohuzi/38/watermark.png", rules ="规则简介：15胡起胡，每多3胡息加一囤，有红黑点胡，\n翻垛跟垛，正宗家乡味。", describe = "十五胡起胡"},
    [39]={ id=39, name="耒阳字牌", type=1, clubtype=1, friends=7, number =3, playerCount = "3", isZuoXing4=0,isVisible=1, icon="game/cdphz/39/icon.png", icons="game/cdphz/39/icon1.png", icon1="game/cdphz/39/icon2.png", icon8="game/cdphz/39/icon8.png", ruleBtn="game/paohuzi/39/rule.png;game/paohuzi/39/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/qlphzwanfa/39.html", imgSynopsiss="game/paohuzi/39/names.png", imgSynopsis="game/paohuzi/39/name.png", luaCreateRoomFile="RoomCreateLayer39", luaGameFile="game.cdphz.39.GameLayer", imgDesk="game/paohuzi/39/watermark.png", rules ="规则简介：10胡起胡,小卡胡(10胡)算16胡,大卡胡(20胡)算24胡,\n10胡牌3囤,11胡牌1囤,12胡2囤,15胡3囤(15胡息后每3胡息加一囤)。", describe = "十胡起胡  可胡放炮"},
    [40]={ id=40, name="衡阳六胡抢", type=1, clubtype=1, friends=7, number =4, playerCount = "4,2,3", isZuoXing4=0,isVisible=1, icon="game/hyphz/40/icon.png", icons="game/hyphz/40/icon1.png", icon1="game/hyphz/40/icon2.png", icon8="game/hyphz/40/icon8.png", ruleBtn="game/paohuzi/40/rule.png;game/paohuzi/40/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/qlphzwanfa/40.html", imgSynopsiss="game/paohuzi/40/names.png", imgSynopsis="game/paohuzi/40/name.png", luaCreateRoomFile="RoomCreateLayer40", luaGameFile="game.hyphz.40.GameLayer", imgDesk="game/paohuzi/40/watermark.png", rules ="规则简介：六胡枪玩的是抢而不是大，胡息数达到6胡并符合\n胡牌牌型就可胡牌。有一五十吃法，没有红黑胡。",describe = "六胡起胡  可胡放炮"},
    [44]={ id=44, name="怀化红拐弯", type=1, clubtype=1, friends=7, number =4, playerCount = "3,2", isZuoXing4=1,isVisible=1, icon="game/huaihua/44/icon.png", icons="game/huaihua/44/icon1.png", icon1="game/huaihua/44/icon2.png", icon8="game/huaihua/44/icon8.png", ruleBtn="game/huaihua/44/rule.png;game/huaihua/44/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/qlphzwanfa/44.html", imgSynopsiss="game/huaihua/44/names.png", imgSynopsis="game/huaihua/44/name.png", luaCreateRoomFile="RoomCreateLayer44", luaGameFile="game.huaihua.44.HHGameLayer", imgDesk="game/huaihua/44/watermark.png", rules ="规则简介：18胡起胡，15胡可自摸胡牌或有名堂胡牌，\n大小字胡4番起，名堂多样，玩法独特。",describe = ""},
    [46]={ id=46, name="转转麻将", type=3, clubtype=3, friends=7, number =4, playerCount = "4,2,3", isZuoXing4=0,isVisible=1, icon="game/majiang/46/icon.png", icons="game/majiang/46/icon1.png", icon1="game/majiang/46/icon2.png", icon8="game/majiang/46/icon8.png", ruleBtn="game/majiang/46/rule.png;game/majiang/46/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/wanfa/46.html", imgSynopsiss="game/majiang/46/names.png", imgSynopsis="game/majiang/46/name.png", luaCreateRoomFile="RoomCreateLayer46", luaGameFile="game.majiang.46.GameLayer", imgDesk="game/majiang/46/watermark.png", rules ="规则简介：可自摸、可接炮，明杠3倍底分，暗杠每人2倍底分，公\n杠1倍底分。自摸2倍底分，中鸟加倍。不能跟胡。只算一五九为鸟。"},
    [47]={ id=47, name="常德红黑点", type=1, clubtype=1, friends=7, number =3, playerCount = "3,2", isZuoXing4=1,isVisible=1, icon="game/cdphz/47/icon.png", icons="game/cdphz/47/icon1.png", icon1="game/cdphz/47/icon2.png", icon8="game/cdphz/47/icon8.png", ruleBtn="game/cdphz/47/rule.png;game/cdphz/47/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/qlphzwanfa/47.html", imgSynopsiss="game/cdphz/47/names.png", imgSynopsis="game/cdphz/47/name.png", luaCreateRoomFile="RoomCreateLayer47", luaGameFile="game.cdphz.47.GameLayer", imgDesk="game/cdphz/47/watermark.png", rules ="规则简介：15胡起胡，经典玩法，红胡、黑胡、点胡，不能接炮，\n只能胡牌墩上的牌。", describe = "十五胡起胡  胡摸的牌"},
    [48]={ id=48, name="常德全名堂", type=1, clubtype=1, friends=7, number =3, playerCount = "3,2", isZuoXing4=1,isVisible=1, icon="game/cdphz/48/icon.png", icons="game/cdphz/48/icon1.png", icon1="game/cdphz/48/icon2.png", icon8="game/cdphz/48/icon8.png", ruleBtn="game/cdphz/48/rule.png;game/cdphz/48/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/qlphzwanfa/48.html", imgSynopsiss="game/cdphz/48/names.png", imgSynopsis="game/cdphz/48/name.png", luaCreateRoomFile="RoomCreateLayer48", luaGameFile="game.cdphz.48.GameLayer", imgDesk="game/cdphz/48/watermark.png", rules ="规则简介：15胡起胡，红胡、黑胡、对对胡、大字胡、小子胡、\n黄番、耍猴等多种名堂，不能接炮，只能胡牌墩上的牌。", describe = "十五胡起胡  胡摸的牌"},
    [49]={ id=49, name="常德多红对", type=1, clubtype=1, friends=7, number =3, playerCount = "3,2", isZuoXing4=1,isVisible=1, icon="game/cdphz/49/icon.png", icons="game/cdphz/49/icon1.png", icon1="game/cdphz/49/icon2.png", icon8="game/cdphz/49/icon8.png", ruleBtn="game/cdphz/49/rule.png;game/cdphz/49/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/qlphzwanfa/49.html", imgSynopsiss="game/cdphz/49/names.png", imgSynopsis="game/cdphz/49/name.png", luaCreateRoomFile="RoomCreateLayer49", luaGameFile="game.cdphz.49.GameLayer", imgDesk="game/cdphz/49/watermark.png", rules ="规则简介：15胡起胡，乌对胡、红对胡等多种特色名堂，\n独特地区玩法，原滋原味，回味无穷。", describe = "十五胡起胡  胡摸的牌"},
    [50]={ id=50, name="长沙麻将", type=3, clubtype=3, friends=7, number =4, playerCount = "4", isZuoXing4=0,isVisible=1, icon="game/majiang/50/icon.png", icons="game/majiang/50/icon1.png", icon1="game/majiang/50/icon2.png", icon8="game/majiang/50/icon8.png", ruleBtn="game/majiang/50/rule.png;game/majiang/50/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/wanfa/50.html", imgSynopsiss="game/majiang/50/names.png", imgSynopsis="game/majiang/50/name.png", luaCreateRoomFile="RoomCreateLayer50", luaGameFile="game.majiang.50.GameLayer", imgDesk="game/majiang/50/watermark.png", rules ="规则简介：胡牌必须有二五八做将，可吃、可碰、可杠、\n可补，胡牌名堂多样变化，胡牌分庄家和闲家。"},
    [60]={ id=60, name="汉寿跑胡子", type=1, clubtype=1, friends=7, number =3, playerCount = "3,2,4", isZuoXing4=1,isVisible=1, icon="game/cdphz/60/icon.png", icons="game/cdphz/60/icon1.png", icon1="game/cdphz/60/icon2.png", icon8="game/cdphz/60/icon8.png", ruleBtn="game/cdphz/60/rule.png;game/cdphz/60/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/wanfa/60.html", imgSynopsiss="game/cdphz/60/names.png", imgSynopsis="game/cdphz/60/name.png", luaCreateRoomFile="RoomCreateLayer60", luaGameFile="game.cdphz.60.GameLayer", imgDesk="game/cdphz/60/watermark.png", rules ="规则简介：15胡起胡，红胡、黑胡、对对胡、大字胡、小子胡、\n黄番、耍猴等多种名堂，不能接炮，只能胡牌墩上的牌。"}, 
    [67]={ id=67, name="王钓麻将", type=3, clubtype=3, friends=7, number =4, playerCount = "4", isZuoXing4=0,isVisible=1, icon="game/majiang/67/icon.png", icons="game/majiang/67/icon1.png", icon1="game/majiang/67/icon2.png", icon8="game/majiang/67/icon8.png", ruleBtn="game/majiang/63/rule.png;game/majiang/67/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/wanfa/63.html", imgSynopsiss="game/majiang/67/names.png", imgSynopsis="game/majiang/67/name.png", luaCreateRoomFile="RoomCreateLayer67", luaGameFile="game.majiang.67.GameLayer", imgDesk="game/majiang/67/watermark.png", rules ="规则简介：8张红中，红中可以代替任何牌，红中不能打出，\n起手4张红中可以直接胡牌。只能自摸，不准接炮。"},
    [68]={ id=68, name="红中麻将", type=3, clubtype=3, friends=7, number =4, playerCount = "4,2,3", isZuoXing4=0,isVisible=1, icon="game/majiang/68/icon.png", icons="game/majiang/68/icon1.png", icon1="game/majiang/68/icon2.png", icon8="game/majiang/68/icon8.png", ruleBtn="game/majiang/68/rule.png;game/majiang/68/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/wanfa/68.html", imgSynopsiss="game/majiang/68/names.png", imgSynopsis="game/majiang/68/name.png", luaCreateRoomFile="RoomCreateLayer68", luaGameFile="game.majiang.68.GameLayer", imgDesk="game/majiang/68/watermark.png", rules ="规则简介：4张红中，红中可以代替任何牌，红中不能打出，\n起手4张红中可以直接胡牌。只能自摸，不准接炮。"}, 
    [69]={ id=69, name="安化跑胡子", type=1, clubtype=1, friends=7, number =4, playerCount = "3,2", isZuoXing4=1,isVisible=1, icon="game/anhua/69/icon.png", icons="game/anhua/69/icon1.png", icon1="game/anhua/69/icon2.png", icon8="game/anhua/69/icon8.png", ruleBtn="game/anhua/69/rule.png;game/anhua/69/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/qlphzwanfa/69.html", imgSynopsiss="game/anhua/69/names.png", imgSynopsis="game/anhua/69/name.png", luaCreateRoomFile="RoomCreateLayer69", luaGameFile="game.anhua.69.GameLayer", imgDesk="game/anhua/69/watermark.png", rules ="规则简介：18胡起胡，15胡可自摸胡牌或有名堂胡牌，\n大小字胡4番起，名堂多样，玩法独特。",describe = ""},
    [70]={ id=70, name="长沙麻将", type=3, clubtype=3, friends=7, number =4, playerCount = "4", isZuoXing4=0,isVisible=1, icon="game/majiang/70/icon.png", icons="game/majiang/70/icon1.png", icon1="game/majiang/70/icon2.png", icon8="game/majiang/70/icon8.png", ruleBtn="game/majiang/70/rule.png;game/majiang/70/rule_1.png", ruleCSB="http://share.hy.qilaigame.com/rule/wanfa/70.html", imgSynopsiss="game/majiang/70/names.png", imgSynopsis="game/majiang/70/name.png", luaCreateRoomFile="RoomCreateLayer70", luaGameFile="game.majiang.70.GameLayer", imgDesk="game/majiang/70/watermark.png", rules ="规则简介：胡牌必须有二五八做将，可吃、可碰、可杠、\n可补，胡牌名堂多样变化，胡牌分庄家和闲家。"},
}

return Games


